# Generated by Django 3.1.7 on 2021-05-13 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('singletonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='actor.singletonmodel')),
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_update', models.TimeField(max_length=45)),
            ],
            bases=('actor.singletonmodel',),
        ),
    ]
