# Generated by Django 3.1.7 on 2021-05-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='last_update',
            field=models.TimeField(max_length=45),
        ),
    ]
